### ISSUE TITLE
'give' command gives only one item

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#13] opened 2015-07-28 12:35 UTC
I found that `give` command always gives me the same item in the config, but not the one I specified.

Using version 3.5.27.

**Comment by phoenixlzx** [comment] 2015-07-28 13:04
The problem seems exists since release v3.5.13, as the config folder name changed.

**Comment by Taiterio** [comment] 2015-07-28 14:06
Investigating, can reproduce this. I thought renaming the project to get rid of the space in the name would be a good idea and I actually checked for possible breakage, seems like I didn't think too far there :/

**Comment by phoenixlzx** [comment] 2015-07-28 14:12
The only change I have noticed so far is the folder name changed, and I'm not sure if any other changes caused this problem.

**Comment by Taiterio** [comment] 2015-07-28 14:29
Found the error, I brought it in when I added the locales in commit a1824a8edb01b941247ef65527eb28e451dec3a9. It's now fixed in commit 908c0ee19a345357636f4b607ec7b87daf371ea1.The problem was that the class RPGItem used a static ItemMeta, so all items it generated had the same Itemmeta... Sorry for this :/

**Closed by Taiterio** 2015-07-28 14:29 UTC
Labels: bug
