### ISSUE TITLE
RPGItems breaking lore in CrazyAuctions!

### ISSUE THREAD

**Issue by durson54** [NyaaCat/RPGitems-reloaded#291] opened 2018-01-27 22:41 UTC
Hello So I tried to sell a RPGItem in CrazyAuctions and it broke lore... It should add to lore who's selling it, price and more... but it doesn't it probably sets its lore how it should be and it won't allow crazy auctions to add their lore to item in auction. Please fix this it's really important because players won't know the price.

**Comment by cyilin** [comment] 2018-01-29 06:44
this bug was fixed in latest version

**Comment by durson54** [comment] 2018-01-31 16:07
I have the latest version and it's happening.

**Comment by cyilin** [comment] 2018-02-01 04:56
![snapshot](https://user-images.githubusercontent.com/12132775/35661727-08fecbda-070c-11e8-822a-b8b8a387daa7.png)
can't reproduce

**Comment by Midnight9746** [comment] 2018-03-11 12:13
If you're still having the problem, regenerate the config file. Sometimes new updates changes the file to allow me methods and bug fixes.

**Closed** 2018-12-11 10:52 UTC
