### ISSUE TITLE
Multiple potionself's on an item not working!

### ISSUE THREAD

**Issue by lilbudgotswag** [NyaaCat/RPGitems-reloaded#215] opened 2017-04-04 23:16 UTC
I've tried to create a weapon where you right click and it gives you multiple buffs such as strength and resistance but for what ever reason having multiple potionself's on an item causes only one of them to work and the other to just be ignored.

**Comment by Librazy** [comment] 2017-04-05 00:26
What version of RPGItems and Minecraft did you use？

**Comment by Librazy** [comment] 2017-11-16 15:44
Maybe duplicate of #259

**Closed by Librazy** 2017-11-16 15:44 UTC
