### ISSUE TITLE
Problem with multiple "PotionSelf" power!

### ISSUE THREAD

**Issue by DawamRM** [NyaaCat/RPGitems-reloaded#228] opened 2017-06-02 15:47 UTC
Since there is a error with the Golden Apple while in PvP, I created an RPGitem with the same powers of a Golden Apple, but it only gives the first potion self, pls help.

**Comment by Librazy** [comment] 2017-11-16 14:55
May be a duplicate of #259. You only need to set cooldown on the last power.

**Closed by Librazy** 2017-11-16 14:55 UTC
