### ISSUE TITLE
Errors for NullPointerException

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/RPGitems-reloaded#342] opened 2018-10-28 09:12 UTC
```
[16:04:35 ERROR]: Could not pass event PlayerInteractEvent to RPGItems v3.6.459-mc1.13.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:267) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:230) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1360) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:172) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:237) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:278) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
at think.rpgitems.power.impl.PowerTeleport.rightClick(PowerTeleport.java:55) ~[?:?]
at think.rpgitems.item.RPGItem.rightClick(RPGItem.java:702) ~[?:?]
at think.rpgitems.Events.onPlayerAction(Events.java:278) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1216.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-1.13.2-R0.1.jar:git-Paper-405]
... 18 more
```

**Comment by Librazy** [comment] 2018-10-29 00:28
duplicate of #43

**Closed by Librazy** 2018-10-29 00:28 UTC
