### ISSUE TITLE
Recipe glitch

### ISSUE THREAD

**Issue by facemywrath** [NyaaCat/RPGitems-reloaded#156] opened 2016-08-27 10:41 UTC
So, first of all I would like to point out that in game it has a CHANCE parameter for the recipe command.
Seen here: http://puu.sh/qQ7M8/1a7d9d2fb5.png
And here: http://puu.sh/qQ7Mr/1d09e3bf77.png

Yes, I'm on 1.10. On my server. As we speak.

Secondly, I would like to inquire as to the ability to use rpgitems in the recipe for other rpgitems. I seem to be having trouble with it to an extent. I think the problem lies in the info that is saved. I would recommend ChatColor.stripColor(), but I'm not sure if that would fix the problem.
Reason why is here: http://puu.sh/qQ7Vs/d68c1c38ff.png

Thanks friends.
-Face

**Comment by phoenixlzx** [comment] 2016-08-27 10:43
And the [wiki page here](https://github.com/NyaaCat/RPGitems-reloaded/wiki/Commands#rpgitem-item-recipe) should be updated with correct parameter.

**Comment by Librazy** [comment] 2017-11-16 15:58
May be a duplicate of #262.
Wiki updated.

**Closed by Librazy** 2017-11-16 15:58 UTC
